basePath: /v1
definitions:
  cmd_api.CreateUserPayload:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  github_com_Ayushmangit_mirrormate_git_internal_store.Role:
    properties:
      desc:
        type: string
      id:
        format: int64
        type: integer
      level:
        type: integer
      name:
        type: string
    type: object
  github_com_Ayushmangit_mirrormate_git_internal_store.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      role:
        $ref: '#/definitions/github_com_Ayushmangit_mirrormate_git_internal_store.Role'
      role_id:
        type: integer
      username:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: SocialNetwork for hiring
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: MirrorMate
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create a new user account
      parameters:
      - description: User registration payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/cmd_api.CreateUserPayload'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_Ayushmangit_mirrormate_git_internal_store.User'
        "400":
          description: Bad Request
          schema: {}
        "409":
          description: Conflict
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create a new user
      tags:
      - users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
